[package]
name = "bevy_cobweb_ui"
description = "UI tools and widgets built with bevy_cobweb"
authors = ["koe <ukoe@protonmail.com>"]
version = "0.0.3"
edition = "2021"
keywords = ["gamedev", "reactive", "ui"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/UkoeHB/bevy_cobweb_ui"

[lib]
path = "src/lib.rs"
doctest = false
test = false

[[test]]
name = "tests"
path = "tests/test/mod.rs"
doctest = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
# Default features.
default = []

# Enables hot-reloading.
hot_reload = ["bevy/file_watcher"]

# Dev features. Enables hot-reloading.
dev = ["hot_reload", "bevy/dynamic_linking"]

[dependencies]
#bevy        = { version = "0.14", default-features = true, features = ["serialize"] }
bevy = { git = "https://github.com/bevyengine/bevy/", rev = "291db3e", default-features = true, features = ["serialize"] }
bevy_cobweb = { version = "0.9" }
serde       = { version = "1.0" }
serde_json  = { version = "1.0", features = ["preserve_order"] }
smol_str    = { version = "0.2" }
smallvec    = { version = "1.13" }
thiserror   = { version = "1.0" }
tracing     = { version = "0.1" }

sickle_ui = { rev = "ca232db", git = "https://github.com/UmbraLuminosa/sickle_ui" }
#sickle_ui = { rev = "7ee7327", git = "https://github.com/UkoeHB/sickle_ui" }

# Localization deps
sys-locale = { version = "0.3" }
fluent = { version = "0.16" }
fluent-langneg = { version = "0.14" }
fluent_content = { version = "0.0.5" }
intl-memoizer = { version = "0.5" }
ron = { version = "0.8" }
serde_yaml = { version = "0.9" }
unic-langid = { version = "0.9", features = ["serde", "unic-langid-macros"] }

# Local sub-crates
bevy_cobweb_ui_derive = { path = "bevy_cobweb_ui_derive", version = "0.1.0" }

[patch.crates-io]
bevy_cobweb = { git = "https://github.com/UkoeHB/bevy_cobweb/", branch = "bevy_main" }

[patch."https://github.com/UmbraLuminosa/sickle_ui"]
sickle_ui = { git = "https://github.com/UkoeHB/sickle_ui/", branch = "bevy_main" }

[dev-dependencies]
tracing-subscriber = { version = "0.3" }

[profile.dev.package."*"]
opt-level = 2

[workspace]
resolver = "2"
members = [
    "examples/counter",
    "examples/counter_widget",
    "examples/localization",
    "examples/radio_buttons",
]
